@echo off
echo Stopping any existing Flask processes...
taskkill /f /im python.exe >nul 2>&1
echo Waiting for processes to close...
timeout /t 2 /nobreak >nul
echo Starting Flask app with enhanced debugging...
cd /d "c:\Users\wanth\hharry\models\python\askmodels"
python unified_app.py
